name: scgen
channels:
  - conda-forge          
  - bioconda             
dependencies:
  - python=3.11
  - scanpy
  - scvi-tools
  - pertpy
  - optuna               
  - jupyterlab           
  - ipywidgets           
  - pip
